### ISSUE TITLE
An invalid date was found. Please fix the date or formatting before resubmitting.

### ISSUE THREAD

**Issue by cosbgn** [nuxt-modules/sitemap#208]
<img width="665" alt="image" src="https://github.com/nuxt-modules/sitemap/assets/17546283/3bfdb9d3-4ef3-4970-82db-79771c667769">

Is generating something like this:

```
<url>
<loc>
https://example.com/blog/how-to-fix-this
</loc>
<lastmod>2024-01-08T00:00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.8</priority>
</url>
```

**Comment by cosbgn** [comment]
I use `nuxt-content` and set:

```
sitemap:
  loc: /blog/how-to-fix-crawled-currently-not-indexed
  lastmod: 2024-01-08
  changefreq: monthly
  priority: 0.8
  ```
  
  The format is correct, but the module then changes it.
